### ISSUE TITLE
KRT-1001 - Revisjonselskapers egenmelding

### ISSUE THREAD

**Issue by gunnarbr** [Altinn/apps-backlog#30]
#### Er tjenesten en ny eller eksisterende tjeneste?
- [] Ny tjeneste
- [x] Eksisterende tjeneste

 Hvis eksisterende, fyll ut tabellen under:
 
 | Beskrivelse av tjenesten | _Legg inn kort beskrivelse_ |
| ------------- | ------------- |
| **Tjenestekode** | _Legg inn tjenestekode (ServiceCode)_  |
| **Tjenesteutgavekode**  |  _Legg inn tjenesteutgavekode (ServiceEditionCode)_ |
| **Tjenestetype**  | Innsending/Innsyn/Melding/Samhandling/Formidling/Annen  |
| **Volum**  | Arkiveringer/Transaksjoner  |
| **Integrasjon**  | _Web Service / SFTP / DownloadQueue_ |
 
#### Skal tjenesten migreres til Altinn 3.0?
- [ ] Skal migreres 
- [x] Skal _IKKE_ migreres
- [ ] Vet ikke

Det er et eksisterende skjema, men som følge av nytt regelverk skal innholdet i skjemaet endres ganske mye. Det vil si at vi i praksis lager et helt nytt skjema.

#### Hvordan benyttes Tjenesten?
- [x] Kun portal-innsending
- [ ] Kun sluttbrukersystem-innsending
- [ ] Både portal- og sluttbrukersystem-innsending

#### Har tjenesten underskjema / skjemasett?
- [ ] Ja
- [x] Nei

#### Er det rollekrav på tjenesten?
- [ ] Ja
- [ ] Nei

Hvis Ja, beskriv rollene og rollekravene nærmere.

#### Hvilket sikkerhetsnivå krever tjenesten?
- [ ] Nivå 0
- [ ] Nivå 1
- [ ] Nivå 2
- [ ] Nivå 3
- [ ] Nivå 4

#### Har tjenesten frister eller andre egenskaper?
- [x] Ja
- [ ] Nei

_Eksempelvis, innsendingsfrist en eller flere ganger i året._

### Integrasjon

| Navn på Grensesnitt| _fyll inn_ |
| ------------- | ------------- |
|Type Grensesnitt| _Web Service / SFTP / DownloadQueue_  |

## Skjermbilder
> Legg inn (relevante) skjermbilder av tjenesten her.

## Bruk av Standard Altinn-funksjonalitet
> Fyll ut

## Lenker og filer

- Lenke til tjeneste-/skjemakatalogen: 

#### Altinn 2

| Område  | Lenke |
| ------------- | ------------- |
| Skjemakatalogen  | https://altinn.no/skjemaoversikt/ ....  |
| TUL  | https://tul.altinn.no/ ....  |
| Altinn 2.0 (test)  | https://tt02.altinn.no/ .... |
| Altinn 2.0 (prod)  | https://altinn.no/ .....  |

- XSD: _Last opp XSD her (i .zip-format)_

#### Altinn 3

| Område  | Lenke |
| ------------- | ------------- |
| Altinn Studio  | https://altinn.no/skjemaoversikt/ ....  |
| Altinn 3.0 (test)  |  ....  |
| Altinn 3.0 (prod)  | .... |

**Comment by stalehalden** [comment]
Test

**Comment by gunnarbr** [comment]
Duplicate of #45
