### ISSUE TITLE
Transportløyvegaranti 

### ISSUE THREAD

**Issue by lvbachmann** [Altinn/apps-backlog#9]
## Is your feature request related to a problem? Please describe
Transportløyvegaranti starts with letting the user search for information about existing guarantees in a database at SVV. The result of that search can be used into two distinct processes - either registering a new guarantee or modifying an existing guarantee. For a new guarantee, the user can identify which guarantee(s) a new guarantee is meant to replace.

## Describe the solution you'd like
Use Altinn/altinn-studio#1328, either as first step in a process or as a standalone service linking to different data input services. Data from the lookup should be available in the instantiated app, including for use in drop-downs etc.

## Early sketch
![POWERPNT_rZjowfboVY](https://user-images.githubusercontent.com/36764011/142408673-8e786e80-296b-4de1-80d3-6dd2ef6677cd.png)

## Nice to have
- Altinn/app-frontend-react#155
- Altinn/altinn-studio#6960 
- Altinn/altinn-studio#7903

### Closed
- Altinn/altinn-studio#7888 
- Altinn/altinn-studio#6139
- Altinn/altinn-studio#6194
- Altinn/altinn-studio#7164 
- Altinn/altinn-studio#6196 
- Altinn/altinn-studio#6514
- Altinn/altinn-studio#7393
- Altinn/altinn-studio#7308
- Altinn/altinn-studio#7893

**Comment by AinaEngen** [comment]
@lorang92 - hva er status på denne? Kan den lukkes? cc: @elwal

**Comment by lorang92** [comment]
@AinaEngen denne appen ligger i produksjon :) Jeg er ikke helt sikker på hvordan prossesen rundt issues er i apps-backlogen. Det ligger jo f.eks to åpne issues her som de har ønsket seg men som ikke stoppet prodsetting.
